// Re-parse BMG to be modifiable easier

use std::{fs, io::Write, path::Path};

use serde::{Deserialize, Serialize};
use strum::FromRepr;

use crate::{parse::{BMG, FontType}, traits::ExistSubstringExt};

pub mod parse;
pub mod traits;

#[derive(Debug, Serialize, Deserialize)]
struct WithSchema<'a, T> {
    #[serde(rename = "$schema")]
    schema: &'a str,
    #[serde(flatten)]
    data: T,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageGroup {
    pub items: Vec<MessageItem>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageItem {
    pub id: u32,
    pub font_type: FontType,
    pub text: String,
}

impl MessageGroup {
    pub fn read_from_path<P: AsRef<Path>>(path: P) -> anyhow::Result<Self> {
        let bmg = BMG::read_from_path(path)?;
        Self::read_from_bmg(bmg)
    }

    pub fn read_from_bmg(data: BMG) -> anyhow::Result<Self> {
        Ok(data.into())
    }

    const SCHEMA_PATH: &str = "https://files.rz-public.xyz/resources/bmg/schema.json";

    pub fn write_to_json<P: AsRef<Path>>(&self, path: P) -> anyhow::Result<()> {
        let mut file = fs::File::create(path)?;
        let data_to_json = WithSchema {
            schema: Self::SCHEMA_PATH,
            data: self,
        };
        let json = serde_json::to_string_pretty(&data_to_json)?;
        file.write(json.as_bytes())?;
        file.flush()?;

        Ok(())
    }
}

#[derive(Debug, FromRepr, PartialEq, Eq, Clone, Copy)]
#[repr(u16)]
pub enum EscapeSequence {
    CurrentPlayerName = 0x0602,
    TextStyle = 0x0800,
    Unicode = 0x0801,
    Context = 0x0802,
    ContextXY = 0x0A02,
    Unknown = 0x0C04,
}

impl EscapeSequence {
    pub fn size(self) -> usize {
        match self {
            EscapeSequence::CurrentPlayerName => 1,
            EscapeSequence::TextStyle | EscapeSequence::Unicode | EscapeSequence::Context => 2,
            EscapeSequence::ContextXY => 3,
            EscapeSequence::Unknown => 4,
        }
    }
}

fn get_text_until_null<P: AsRef<Vec<u16>>>(pool: P, offset: usize) -> String {
    let pool = &pool.as_ref()[offset..pool.as_ref().len()];
    let mut pool_iter = pool.iter().peekable();
    let mut result: Vec<u16> = vec![];
    while let Some(&code) = pool_iter.next() {
        match code {
            0x001a => {
                result.push(code);
                if let Some(&size) = pool_iter.next() {
                    result.push(size);
                    if let Some(seq) = EscapeSequence::from_repr(size) {
                        for _ in 0..seq.size() {
                            if let Some(&d) = pool_iter.next() {
                                result.push(d);
                            }
                        }
                    }
                }
            }
            0x0000 => break,
            _ => result.push(code),
        }
    }
    String::from_utf16_lossy(&result)
}

impl ExistSubstringExt for Vec<u16> {
    fn check_substring_exist(&self, sub: &[u16]) -> Option<usize> {
        self.windows(sub.len()).position(|w| w == sub)
    }
}

#[cfg(test)]
mod tests {
    use std::{fs, io::Write, path::Path};

    use binrw::BinWrite as _;

    use crate::{MessageGroup, parse::BMG};

    #[test]
    fn get_data_from_bmg() -> anyhow::Result<()> {
        let bmg = BMG::read_from_path("test/Race.bmg")?;
        let msg = MessageGroup::read_from_bmg(bmg)?;
        println!("{msg:?}");

        Ok(())
    }

    #[test]
    fn test_write_to_json() -> anyhow::Result<()> {
        let bmg = BMG::read_from_path("test/Race.bmg")?;
        let msg = MessageGroup::read_from_bmg(bmg)?;
        msg.write_to_json("test/Race.json")?;

        Ok(())
    }

    #[test]
    fn test_write_to_binary() -> anyhow::Result<()> {
        let bmg = BMG::read_from_path("test/Race.bmg")?;
        let msg = MessageGroup::read_from_bmg(bmg)?;
        let bmg_re_encode = BMG::from(msg);

        let path = Path::new("test/Race_reencode.bmg");
        let mut bmg_dest = fs::File::create(path)?;
        bmg_re_encode.write_be(&mut bmg_dest)?;
        bmg_dest.write(b"Generated by mkwii-distro-tool")?;
        bmg_dest.flush()?;

        Ok(())
    }
}
